{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dmf-control-board-firmware
  version: {{ GIT_VERSION }}

requirements:
  build:
    - dmf-control-board-firmware-develop  # Dev dependencies meta-package
    - scons

  run:
    # Arduino dependencies
    - platformio-helpers
    - platformio-tool-scons
    - platformio-tool-avrdude
    - python 2.7*

    # Python dependencies
    - arrow
    - base-node
    - conda-helpers >=0.4
    - functools32
    - matplotlib
    - microdrop-utility
    - pandas
    - pytables
    - scipy
    - serial-device
    - svg-model
    - sympy

test:
  imports:
    - dmf_control_board_firmware

about:
  home: https://github.com/wheeler-microfluidics/dmf-control-board-firmware
  license: BSD
